/* eslint-disable @next/next/no-img-element */
import React, { useContext } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { Store } from '../utils/Store';
export default function Layout({ title, children }) {
  const { state, dispatch } = useContext(Store);
  const { cart } = state;
  return (
    <>
      <Head>
        <title>
          {title ? title + ' (ZeroTo5 E-Store)' : 'ZeroTo5 E-Store'}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-16 items-center px-4 justify-between shadow-md">
            <Link href="/" className="text-lg font-bold">
              <img src="/images/logo.png" alt="ZeroTo5" />
            </Link>
            <div className="flex">
              <Link href="/cart" className="flex-col p-2">
                <div className="grid grid-cols-2">
                  <img src="/images/icons/cart.png" alt="Cart" width={35} />
                  {cart.cartItems.length > 0 && (
                    <span className="ml-1 rounded-full bg-red-600 px-1 py-1 text-xs font-bold text-white w-6 h-6 text-center">
                      {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                    </span>
                  )}
                </div>
              </Link>
              <Link href="/login" className="flex-col p-2">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner">
          Footer
        </footer>
      </div>
    </>
  );
}
