import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Zeroto5',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Divya',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  categories: [
    "Infants","Boys", "Girls", "Toys", "Accessories", "Footwears", "Fancy", "Innerwears" 
  ],
  products:[{
    "name": "Buzzee Baby Rombers Half",
    "slug": "half_rombers",
    "category": "Infants",
    "image": "/images/romber1.jpg",
    "price": 499,
    "brand": "Buzzee",
    "rating": 4.5,
    "numReviews": 8,
    "countInStock": 4,
    "description": "Best for your babies in the month group",
    "isFeatured": true,
    "banner": "/images/banner1.jpg",
    "isLatest": false,
    "onSale": false
  },{
    "name": "Buzzee Baby Rombers Girls",
    "slug": "girl_rombers",
    "category": "Infants",
    "image": "/images/romber2.jpg",
    "price": 699,
    "brand": "Buzzee",
    "rating": 4.7,
    "numReviews": 7,
    "countInStock": 4,
    "description": "Best for your babies in the month group",
    "isFeatured": true,
    "banner": "/images/banner2.jpg",
    "isLatest": false,
    "onSale": false
  },{
    "name": "Buzzee Baby Rombers Full",
    "slug": "full_rombers",
    "category": "Infants",
    "image": "/images/romber3.jpg",
    "price": 599,
    "brand": "Buzzee",
    "rating": 4.2,
    "numReviews": 5,
    "countInStock": 6,
    "description": "Best for your babies in the month group",
    "isFeatured": true,
    "banner": "/images/banner3.jpg",
    "isLatest": false,
    "onSale": false
  },{
    "name": "Baby Santa Rombers",
    "slug": "santa_rombers",
    "category": "Infants",
    "image": "/images/santa_romber.jpg",
    "price": 459,
    "brand": "HappyKid",
    "rating": 3.5,
    "numReviews": 7,
    "countInStock": 10,
    "description": "HappyKid Christmas Special",
    "isFeatured": true,
    "banner": "/images/banner4.jpg",
    "isLatest": false,
    "onSale": false
  },{
    "name": "Baby Rombers Grey Red",
    "slug": "rombers_grey",
    "category": "Infants",
    "image": "/images/romber4.jpg",
    "price": 359,
    "brand": "HappyKid",
    "rating": 3.9,
    "numReviews": 10,
    "countInStock": 9,
    "description": "HappyKid Christmas Special",
    "isFeatured": false,
    "isLatest": false,
    "onSale": false,
    "banner": "/images/banner8.jpg"
  },{
    "name": "Baby Hoodie Set",
    "slug": "hoodieset",
    "category": "Infants",
    "image": "/images/hoodieset.jpg",
    "price": 559,
    "brand": "HappyKid",
    "rating": 4.9,
    "numReviews": 20,
    "countInStock": 5,
    "description": "HappyKid Winter Special Hoodie Set",
    "isFeatured": false,
    "isLatest": false,
    "onSale": false,
    "banner": "/images/banner6.jpg"
  },{
    "name": "Dummy Item",
    "slug": "testing",
    "category": "Infants",
    "image": "/images/testing.jpg",
    "price": 10,
    "brand": "DUMMY",
    "rating": 4.9,
    "numReviews": 20,
    "countInStock": 100,
    "description": "DUMMY Item added for testing payment",
    "isFeatured": false,
    "onSale": true,
    "isLatest": true,
    "banner": "/image/banner7.jpg"
  },{
    "name": "ZT5 Teddy Bear",
    "slug": "teddybear1",
    "category": "Toys",
    "image": "/images/teddy.jpg",
    "price": 25,
    "brand": "ZT5",
    "rating": 0,
    "numReviews": 0,
    "countInStock": 10,
    "description": "Soft Toys",
    "isFeatured": true,
    "banner": "images/banner5.jpg",
    "isLatest": true,
    "onSale": true
  },{
    "name": "Cute Walk Green Baby shoes",
    "slug": "slug0.6418087076894694",
    "category": "Footwears",
    "image": "https://res.cloudinary.com/zeroto5/image/upload/v1675939970/nskpms5jklvowb4imfxc.webp",
    "price": 649,
    "brand": "Cute Walk",
    "rating": 0,
    "numReviews": 0,
    "countInStock": 3,
    "description": "Add Description",
    "isFeatured": false,
    "banner": "/images/banner1.jpg",
    "isLatest": true,
    "onSale": true
  }]
};

export default data;
