import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Zeroto5',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Divya',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Buzzee Baby Rombers Half',
      slug: 'half_rombers',
      category: 'Infants',
      image: '/images/romber1.jpg',
      price: 499,
      brand: 'Buzzee',
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
      description: 'Best for your babies in the month group',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Buzzee Baby Rombers Girls',
      slug: 'girl_rombers',
      category: 'Infants',
      image: '/images/romber2.jpg',
      price: 699,
      brand: 'Buzzee',
      rating: 4.7,
      numReviews: 7,
      countInStock: 4,
      description: 'Best for your babies in the month group',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Buzzee Baby Rombers Full',
      slug: 'full_rombers',
      category: 'Infants',
      image: '/images/romber3.jpg',
      price: 599,
      brand: 'Buzzee',
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
      description: 'Best for your babies in the month group',
      isFeatured: true,
      banner: '/images/banner3.jpg',
    },
    {
      name: 'Baby Santa Rombers',
      slug: 'santa_rombers',
      category: 'Infants',
      image: '/images/santa_romber.jpg',
      price: 459,
      brand: 'HappyKid',
      rating: 3.5,
      numReviews: 7,
      countInStock: 10,
      description: 'HappyKid Christmas Special',
      isFeatured: true,
      banner: '/images/banner4.jpg',
    },
    {
      name: 'Baby Rombers Grey Red',
      slug: 'rombers_grey',
      category: 'Infants',
      image: '/images/romber4.jpg',
      price: 359,
      brand: 'HappyKid',
      rating: 3.9,
      numReviews: 10,
      countInStock: 9,
      description: 'HappyKid Christmas Special',
    },
    {
      name: 'Baby Hoodie Set',
      slug: 'hoodieset',
      category: 'Infants',
      image: '/images/hoodieset.jpg',
      price: 559,
      brand: 'HappyKid',
      rating: 4.9,
      numReviews: 20,
      countInStock: 5,
      description: 'HappyKid Winter Special Hoodie Set',
    },
    {
      name: 'Dummy Item',
      slug: 'testing',
      category: 'Infants',
      image: '/images/testing.jpg',
      price: 1,
      brand: 'DUMMY',
      rating: 4.9,
      numReviews: 20,
      countInStock: 100,
      description: 'DUMMY Item added for testing payment',
    },
  ],
};

export default data;
